# Description: Backs up all SharePoint Online site collections to a network share and emails a status report
# Requirements: SharePoint Management Shell (on-premises), write access to backup share
param(
    [string]$SMTPServer    = 'smtp.domain.local',
    [string]$FromAddress   = 'sharepoint-backups@domain.local',
    [string]$ToAddress     = 'admin@domain.local',
    [string]$BackupRoot    = '\\fileserver\Backups\SharePoint\SiteCollections'
)

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

$Hostname   = [System.Net.Dns]::GetHostName()
$Today      = Get-Date -UFormat '%Y%m%d'
$FolderName = Join-Path $BackupRoot $Today

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$DataTable = New-Object System.Data.DataTable
foreach ($Col in @('URL','WebApp','Owner','Size','Status','BackupPath')) {
    $DataTable.Columns.Add((New-Object System.Data.DataColumn $Col, ([string])))
}

try {
    if (-not (Test-Path $FolderName)) { New-Item -Path $FolderName -ItemType Directory -Force | Out-Null }

    foreach ($Site in (Get-SPSite -Limit ALL | Where-Object { $_.Port -eq 443 })) {
        $BackupFile = Join-Path $FolderName ($Site.RootWeb.Title + '.bak')
        $Row = $DataTable.NewRow()
        $Row.URL        = $Site.Url
        $Row.WebApp     = $Site.WebApplication.DisplayName
        $Row.Owner      = $Site.Owner.DisplayName
        $Row.BackupPath = $BackupFile
        $DataTable.Rows.Add($Row)
    }

    foreach ($Record in $DataTable) {
        Backup-SPSite $Record.URL -Path $Record.BackupPath
        if (Test-Path $Record.BackupPath) {
            ($DataTable.Rows | Where-Object URL -eq $Record.URL).Status = 'Completed'
            $SizeMB = '{0:N2}' -f ((Get-Item $Record.BackupPath).Length / 1MB)
            ($DataTable.Rows | Where-Object URL -eq $Record.URL).Size   = $SizeMB
        } else {
            ($DataTable.Rows | Where-Object URL -eq $Record.URL).Status = 'Failed'
        }
    }
} catch {
    $Email.Subject = 'SharePoint Backup Error'
    $Email.Body    = "Error: $($_.Exception.Message)<BR>Generated by <B>$Hostname</B>"
    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
    throw
}

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table style="width:1000px"><tr><td>URL</td><td>Web Application</td><td>Owner</td><td>Size (MB)</td><td>Status</td></tr>'
foreach ($Row in $DataTable) {
    $HTMLTable += "<tr><td>$($Row.Url)</td><td>$($Row.WebApp)</td><td>$($Row.Owner)</td><td align=right>$($Row.Size)</td><td>$($Row.Status)</td></tr>"
}
$HTMLTable += '</table><BR>'

$Email.Subject = 'SharePoint Backup Completed'
$Email.Body    = "$HTMLTable<BR>Generated by <B>$Hostname</B>"

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
