# Description: Warms up all SharePoint web applications and the ADFS login page, then emails a status report
# Requirements: SharePoint Management Shell (on-premises)
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'sharepoint-alerts@domain.local',
    [string]$ToAddress   = 'admin@domain.local',
    [string]$ADFSUrl     = 'https://adfs.domain.local/adfs/ls/IdpInitiatedSignon.aspx'
)

Add-PSSnapin Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

$Hostname = [System.Net.Dns]::GetHostName()
$Today    = Get-Date -UFormat '%D'

$DataTable = New-Object System.Data.DataTable
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Site',     ([string])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Response', ([string])))

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

foreach ($App in (Get-SPWebApplication -IncludeCentralAdministration)) {
    $Response = Invoke-WebRequest -Uri $App.URL -UseDefaultCredentials
    $Row = $DataTable.NewRow(); $Row.Site = $App.DisplayName; $Row.Response = $Response.StatusCode
    $DataTable.Rows.Add($Row)
}

# Also warm up ADFS
$ADFSResponse = Invoke-WebRequest -Uri $ADFSUrl -UseDefaultCredentials
$Row = $DataTable.NewRow(); $Row.Site = 'ADFS Provider'; $Row.Response = $ADFSResponse.StatusCode
$DataTable.Rows.Add($Row)

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>Site</td><td>Response</td></tr>'
foreach ($Row in $DataTable) {
    $HTMLTable += "<tr><td>$($Row.Site)</td><td>$($Row.Response)</td></tr>"
}
$HTMLTable += '</table><BR>'

$Email.Subject = "SharePoint Wakeup - $Today"
$Email.Body    = "The following SharePoint sites have been awakened.<BR><BR>$HTMLTable<BR>Generated by <B>$Hostname</B>"

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
