# Description: Uploads files modified in the last 24 hours from a local/network folder to a SharePoint Online document library
# Requirements: PnP PowerShell module (Install-Module PnP.PowerShell)
param(
    [Parameter(Mandatory)][string]$SiteURL,         # e.g. 'https://contoso.sharepoint.com/sites/MySite'
    [Parameter(Mandatory)][string]$DocLibName,      # Document library name
    [string]$SourceFolder   = 'C:\UploadSource',
    [PSCredential]$Credential = (Get-Credential -Message 'Enter SharePoint Online credentials'),
    [string]$SMTPServer     = 'smtp.domain.local',
    [string]$FromAddress    = 'sharepoint-uploads@domain.local',
    [string]$ToAddress      = 'admin@domain.local'
)

$Hostname = [System.Net.Dns]::GetHostName()
$Today    = Get-Date

Connect-PnPOnline -Url $SiteURL -Credentials $Credential

$Uploaded = 0
foreach ($File in (Get-ChildItem $SourceFolder -File | Where-Object { $_.LastWriteTime -gt $Today.AddDays(-1) })) {
    Add-PnPFile -Path $File.FullName -Folder $DocLibName
    $Uploaded++
}

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true
$Email.Subject = "SharePoint Upload Complete - $($Today.ToString('yyyy-MM-dd'))"
$Email.Body    = "<P>$Uploaded file(s) uploaded to <B>$DocLibName</B> on <B>$SiteURL</B>.</P><P>Generated by <B>$Hostname</B></P>"

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
