# Description: Generates a daily mail flow report (external sent, internal sent, received) for a date range
# Requirements: Exchange Management Shell (E2010 snapin or Exchange 2016 EMS)
param(
    [string]$SMTPServer    = 'smtp.domain.local',
    [string]$FromAddress   = 'exchange-reports@domain.local',
    [string]$ToAddress     = 'ops@domain.local',
    [string]$JournalAddress = 'journal@domain.local',
    [string]$TransportServer = $env:COMPUTERNAME,
    [datetime]$StartDate   = (Get-Date).AddDays(-7).Date,
    [datetime]$EndDate     = (Get-Date).Date,
    [string]$ReportPath    = 'C:\Scripts\Reports\MailFlow\'
)

Add-PSSnapin Microsoft.Exchange.Management.PowerShell.E2010 -ErrorAction SilentlyContinue

$Hostname  = [System.Net.Dns]::GetHostName()
$Email     = New-Object Net.Mail.MailMessage
$Email.From     = $FromAddress
$Email.Sender   = $FromAddress
$Email.ReplyTo  = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$DataTable = New-Object System.Data.DataTable
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Date',     ([string])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'ExtSent',  ([int])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'IntSent',  ([int])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Received', ([int])))

$Server  = Get-TransportServer -Identity $TransportServer
$Current = $StartDate

do {
    $Messages = Get-MessageTrackingLog -Server $Server -ResultSize Unlimited -Start $Current -End $Current.AddDays(1)
    $DailyReceived = ($Messages | Where-Object { $_.EventID -eq 'Deliver' -and $_.Recipients -notcontains $JournalAddress }).Count
    $DailyExtSent  = ($Messages | Where-Object { $_.EventID -eq 'Send'    -and $_.Recipients -notcontains $JournalAddress }).Count
    $DailyIntSent  = ($Messages | Where-Object { $_.EventID -eq 'Deliver' -and $_.Recipients -notcontains $JournalAddress -and $_.Source -eq 'STOREDRIVER' -and $_.Sender -match $env:USERDNSDOMAIN }).Count

    $Row          = $DataTable.NewRow()
    $Row.Date     = $Current.ToShortDateString()
    $Row.ExtSent  = $DailyExtSent
    $Row.IntSent  = $DailyIntSent
    $Row.Received = $DailyReceived
    $DataTable.Rows.Add($Row)
    $Current = $Current.AddDays(1)
} while ($Current -lt $EndDate.AddDays(1))

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table style="width:700px"><tr><td align=center>Date</td><td align=center>External Sent</td><td align=center>Internal Sent</td><td align=center>Total Received</td></tr>'
foreach ($Row in ($DataTable | Sort-Object Date)) {
    $HTMLTable += "<tr><td>$($Row.Date)</td><td align=right>$($Row.ExtSent)</td><td align=right>$($Row.IntSent)</td><td align=right>$($Row.Received)</td></tr>"
}
$HTMLTable += '</table><BR>'

$Email.Subject = "Exchange Mail Flow Report - $(Get-Date -Format 'yyyy-MM-dd')"
$Email.Body    = "$HTMLTable<BR><I>Generated by <B>$Hostname</B></I>"

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
