# Description: Monitors Exchange event log for backpressure errors every 5 minutes.
#              If C: drive free space is below threshold, automatically clears old Exchange/IIS logs.
# Requirements: Exchange Management Shell, run as scheduled task every 5 minutes
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'exchange-alerts@domain.local',
    [string]$ToAddress   = 'ops@domain.local',
    [double]$DiskThreshold = 0.20,
    [int]$LogRetentionDays  = 1,
    [string]$IISLogPath         = 'C:\inetpub\logs\LogFiles\',
    [string]$ExchangeLogPath    = 'C:\Program Files\Microsoft\Exchange Server\V15\Logging\',
    [string]$ETLLogPath         = 'C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Diagnostics\ETLTraces\',
    [string]$ETLLogPath2        = 'C:\Program Files\Microsoft\Exchange Server\V15\Bin\Search\Ceres\Diagnostics\Logs'
)

$ScriptStartTime = Get-Date
$Hostname   = [System.Net.Dns]::GetHostName()
$EventID    = 15006
$ErrorExist = $false
$LowDisk    = $false

$Email          = New-Object Net.Mail.MailMessage
$Email.From     = $FromAddress
$Email.Sender   = $FromAddress
$Email.ReplyTo  = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$DataTable = New-Object System.Data.DataTable
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'EventID', ([string])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Time',    ([datetime])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Message', ([string])))

$Drive = Get-PSDrive -Name C
$FreePercent     = $Drive.Free / ($Drive.Used + $Drive.Free)
$FriendlyPercent = $FreePercent.ToString('p')
if ($FreePercent -lt $DiskThreshold) { $LowDisk = $true }

$Events = Get-EventLog -LogName Application -After (Get-Date).AddMinutes(-5)
$Errors = $Events | Where-Object { $_.EventID -eq $EventID }
if ($Errors.Count -gt 0) {
    $ErrorExist = $true
    foreach ($Event in $Errors) {
        $Row         = $DataTable.NewRow()
        $Row.EventID = $Event.EventID
        $Row.Message = $Event.Message.Split('.')[0]
        $Row.Time    = [DateTime]$Event.TimeGenerated
        $DataTable.Rows.Add($Row)
    }
}

function Remove-OldLogFiles {
    param([string]$TargetFolder)
    if (Test-Path $TargetFolder) {
        $Cutoff = (Get-Date).AddDays(-$LogRetentionDays)
        Get-ChildItem $TargetFolder -Include *.log -Recurse |
            Where-Object { $_.LastWriteTime -le $Cutoff } |
            Remove-Item -ErrorAction SilentlyContinue
    } else {
        Write-Warning "Log folder not found: $TargetFolder"
    }
}

if ($LowDisk) {
    Remove-OldLogFiles $IISLogPath
    Remove-OldLogFiles $ExchangeLogPath
    Remove-OldLogFiles $ETLLogPath
    Remove-OldLogFiles $ETLLogPath2
}

if ($ErrorExist) {
    $HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>Event ID</td><td>Event Time</td><td>Message</td></tr>'
    foreach ($Row in ($DataTable | Sort-Object Time)) {
        $HTMLTable += "<tr><td>$($Row.EventID)</td><td>$(Get-Date $Row.Time -Format 'dd/MM/yyyy HH:mm:ss')</td><td>$($Row.Message)</td></tr>"
    }
    $HTMLTable += '</table><BR>'

    $Speed = [Math]::Round((New-TimeSpan -Start $ScriptStartTime -End (Get-Date)).TotalSeconds, 2)

    if ($LowDisk) {
        $Drive           = Get-PSDrive -Name C
        $NewFreePercent  = $Drive.Free / ($Drive.Used + $Drive.Free)
        $Email.Subject   = 'Backpressure on Exchange (Low Disk Space)'
        $Email.Body      = "<P>Exchange is experiencing backpressure due to <b>low disk space</b> on C:.</P><P>Automatic log cleanup triggered (logs older than $LogRetentionDays day(s) removed).</P><P>Free space before: $FriendlyPercent | After: $($NewFreePercent.ToString('p'))</P><P>$HTMLTable</P><P>Generated by <B>$Hostname</B> in <B>$Speed</B> seconds.</P>"
    } else {
        $Email.Subject = 'Backpressure on Exchange (Investigation Required)'
        $Email.Body    = "<P>Exchange is experiencing backpressure not related to disk space. External inbound email may be affected.</P><P><B>Please investigate immediately.</B></P><P>$HTMLTable</P><P>Generated by <B>$Hostname</B> in <B>$Speed</B> seconds.</P>"
    }

    $Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
    $Smtp.Send($Email)
}
