# Description: Retrieves soft-deleted emails from a mailbox for the past N days and emails an HTML report
# Requirements: Exchange Management Shell, Mailbox Import Export management role
#   Assign role: New-ManagementRoleAssignment -Role 'Mailbox Import Export' -User 'admin@domain.local'
param(
    [string]$SMTPServer     = 'smtp.domain.local',
    [string]$FromAddress    = 'exchange-reports@domain.local',
    [string]$ToAddress      = 'admin@domain.local',
    [string]$MonitoredMailbox = 'monitored-mailbox@domain.local',
    [int]$DaysBack          = 5
)

Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn -ErrorAction SilentlyContinue

$Hostname  = [System.Net.Dns]::GetHostName()
$FromDate  = (Get-Date).AddDays(-$DaysBack).ToLongDateString()
$ToDate    = (Get-Date).ToLongDateString()

$Items = Get-RecoverableItems -Identity $MonitoredMailbox `
                              -FilterItemType IPM.Note `
                              -FilterStartTime (Get-Date).AddDays(-$DaysBack) |
         Select-Object Identity, Subject, SourceFolder, LastModifiedTime |
         ConvertTo-Html

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true
$Email.Subject = "Mailbox Deletions Report: $FromDate to $ToDate"
$Email.Body    = "$Items<BR><I>Generated by <B>$Hostname</B></I>"

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
