# Description: Compares an application error log against a previous snapshot; emails new lines found.
#              Run as a scheduled task to detect new errors since the last check.
param(
    [string]$SMTPServer   = 'smtp.domain.local',
    [string]$FromAddress  = 'app-monitor@domain.local',
    [string]$ToAddress    = 'ops@domain.local',
    [string]$LogFile      = 'E:\App\Logs\Error.log',   # Path to the application error log
    [string]$SnapshotFile = 'C:\Scripts\Error.log.old'  # Previous snapshot for comparison
)

$Hostname = [System.Net.Dns]::GetHostName()

$NewErrors = Compare-Object (Get-Content $LogFile) (Get-Content $SnapshotFile) -PassThru

if ($NewErrors) {
    $Date = $NewErrors[0].Substring(0, 10)
    $Time = $NewErrors[0].Substring(11, 8)

    $Body = "New errors detected in application error log on <B>$Hostname</B>.<BR><BR>"
    $Body += "Date: $Date<BR>Time: $Time<BR><BR>"
    foreach ($Line in $NewErrors) { $Body += "$Line<BR>" }
    $Body += "<BR>Generated by <B>$Hostname</B>"

    $Email         = New-Object Net.Mail.MailMessage
    $Email.From    = $FromAddress
    $Email.Sender  = $FromAddress
    $Email.ReplyTo = $FromAddress
    $Email.To.Add($ToAddress)
    $Email.IsBodyHtml = $true
    $Email.Subject = "New Errors in Application Log on $Hostname"
    $Email.Body    = $Body

    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
}

# Update snapshot with current log contents
Copy-Item $LogFile $SnapshotFile -Force
