# Description: Checks the DFS Replication event log for errors in the last N hours and emails an alert
# Requirements: DFSR event log access, run on a DC or member server with DFS-R
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'dfsr-monitor@domain.local',
    [string]$ToAddress   = 'ops@domain.local',
    [int]$LookbackHours  = 4
)

$Hostname = [System.Net.Dns]::GetHostName()
$Now      = Get-Date

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$DataTable = New-Object System.Data.DataTable
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'EventID', ([string])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Time',    ([datetime])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Message', ([string])))

$Events = Get-EventLog -LogName 'DFS Replication' -After $Now.AddHours(-$LookbackHours)
$Errors = $Events | Where-Object { $_.EntryType -eq 'Error' }

if ($Errors.Count -gt 0) {
    foreach ($Event in $Errors) {
        $Row         = $DataTable.NewRow()
        $Row.EventID = $Event.EventID
        $Row.Message = $Event.Message.Split('.')[0]
        $Row.Time    = [DateTime]$Event.TimeGenerated
        $DataTable.Rows.Add($Row)
    }

    $HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>Event ID</td><td>Event Time</td><td>Message</td></tr>'
    foreach ($Row in ($DataTable | Sort-Object Time)) {
        $HTMLTable += "<tr><td>$($Row.EventID)</td><td>$(Get-Date $Row.Time -Format 'dd/MM/yyyy HH:mm:ss')</td><td>$($Row.Message)</td></tr>"
    }
    $HTMLTable += '</table><BR>'

    $Email.Subject = 'DFSR Errors Detected'
    $Email.Body    = "<P>The following errors were detected in the DFS Replication event log in the last $LookbackHours hour(s):</P><P>$HTMLTable</P><P>Generated by <B>$Hostname</B></P>"
    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
}
