# Description: Checks the Security event log on a list of servers for event 1104 (log full) and emails an alert
# Requirements: Remote event log access to target servers
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'security-monitor@domain.local',
    [string]$ToAddress   = 'admin@domain.local',
    [string[]]$Servers   = @('server1.domain.local', 'server2.domain.local'),
    [int]$EventID        = 1104   # 1104 = Security log is full
)

$Hostname = [System.Net.Dns]::GetHostName()
$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

foreach ($Server in $Servers) {
    $Events = Get-EventLog -LogName Security -Newest 10 -ComputerName $Server
    foreach ($Event in $Events) {
        if ($Event.InstanceID -eq $EventID) {
            $Email.Subject = "Security Event Log on $Server is Full"
            $Email.Body    = "The Security event log on <B>$Server</B> is full. No further security events will be recorded until the log is cleared.<BR><BR>Event detail:<BR>$($Event | Format-List | Out-String)<BR>Generated by <B>$Hostname</B>"
            (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
        }
    }
}
