# Description: Pings all servers listed in a SQL database, sends SMS and email alerts when a server
#              stops responding, and updates the last-seen timestamp in the database.
# Requirements: SQL Server with a server monitor database (see table structure below), SMS gateway
# SQL Setup:
#   Table 'Serverlist': ServerName NVARCHAR, IPAddress NVARCHAR, LastResponse NVARCHAR, LastAlert NVARCHAR
#   Table 'Users': Email NVARCHAR, Mobile NVARCHAR, SendSMS BIT
param(
    [string]$SMTPServer   = 'smtp.domain.local',
    [string]$FromAddress  = 'server-alerts@domain.local',
    [string]$SQLServer    = 'sqlserver.domain.local',
    [string]$SQLDatabase  = 'ServerMonitoring',
    [string]$SMSGatewayUrl = 'http://sms-gateway.domain.local/api/sendsms',  # Adapt to your SMS gateway API
    [int]$AlertIntervalMinutes = 10
)

$Hostname = [System.Net.Dns]::GetHostName()
$Now      = Get-Date

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.IsBodyHtml = $true

function Invoke-SQL {
    param([string]$Query)
    $Conn = New-Object System.Data.SqlClient.SqlConnection("Server=$SQLServer;Database=$SQLDatabase;Integrated Security=True;Connect Timeout=0")
    $Cmd  = $Conn.CreateCommand(); $Cmd.CommandText = $Query
    $Conn.Open(); $Cmd.ExecuteNonQuery(); $Conn.Close()
}

function Get-SQLTable {
    param([string]$Table)
    $Conn   = New-Object System.Data.SqlClient.SqlConnection("Server=$SQLServer;Database=$SQLDatabase;Integrated Security=True;Connect Timeout=0")
    $Cmd    = $Conn.CreateCommand(); $Cmd.CommandText = "SELECT * FROM $Table"
    $DA     = New-Object System.Data.SqlClient.SqlDataAdapter $Cmd
    $DT     = New-Object System.Data.DataTable
    $DA.Fill($DT); $Conn.Close()
    return $DT
}

$UserTable  = Get-SQLTable 'Users'
$ServerList = Get-SQLTable 'Serverlist'

# Initialise null LastAlert entries to now
foreach ($Server in ($ServerList | Where-Object { $null -eq $_.LastAlert })) {
    Invoke-SQL "UPDATE Serverlist SET LastAlert='$($Now.ToString('yyyyMMddHHmmss'))' WHERE ServerName='$($Server.ServerName)'"
    $Server.LastAlert = $Now.ToString('yyyyMMddHHmmss')
}

foreach ($Server in $ServerList) {
    $LastAlert = [datetime]::ParseExact($Server.LastAlert, 'yyyyMMddHHmmss', $null)

    if (Test-Connection -ComputerName $Server.IPAddress -Quiet -Count 2) {
        Invoke-SQL "UPDATE Serverlist SET LastResponse='$($Now.ToString('yyyyMMddHHmmss'))' WHERE ServerName='$($Server.ServerName)'"
    } elseif ($LastAlert -lt $Now.AddMinutes(-$AlertIntervalMinutes)) {
        $AlertTime    = $Now.ToString('HH:mm dd-MM-yyyy')
        $LastResponse = [datetime]::ParseExact($Server.LastResponse, 'yyyyMMddHHmmss', $null)
        $AlertText    = "$($Server.ServerName) is not responding at $AlertTime"

        Invoke-SQL "UPDATE Serverlist SET LastAlert='$($Now.ToString('yyyyMMddHHmmss'))' WHERE ServerName='$($Server.ServerName)'"

        foreach ($User in ($UserTable | Where-Object { $_.SendSMS -eq 1 })) {
            # Adapt this URL to your SMS gateway API format
            $SMSURL = "$SMSGatewayUrl`?to=$($User.Mobile)&msg=$AlertText"
            Invoke-WebRequest $SMSURL -UseDefaultCredentials | Out-Null
            $Email.To.Add($User.Email)
        }

        $Email.Subject = "$($Server.ServerName) is not responding"
        $Email.Body    = "$AlertText<BR><BR>Last response: $LastResponse<BR>Generated by <B>$Hostname</B>"
        (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
        $Email.To.Clear()
    }
}
