# Description: Checks that a web service URL returns HTTP 200 and emails an alert if it does not
# Requirements: Network access to the target URL
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'web-monitor@domain.local',
    [string]$ToAddress   = 'ops@domain.local',
    [string]$URL         = 'https://service.domain.local/api/health',
    [string]$ServiceName = 'Web Service'    # Friendly name for email subject
)

$Hostname = [System.Net.Dns]::GetHostName()

try {
    $Response     = [System.Net.WebRequest]::Create($URL).GetResponse()
    $ResponseCode = [int]$Response.StatusCode
} catch {
    $ResponseCode = -1
}

if ($ResponseCode -ne 200) {
    $Email         = New-Object Net.Mail.MailMessage
    $Email.From    = $FromAddress
    $Email.Sender  = $FromAddress
    $Email.ReplyTo = $FromAddress
    $Email.To.Add($ToAddress)
    $Email.IsBodyHtml = $true
    $Email.Subject = "$ServiceName is not responding"
    $Email.Body    = "<P><B>$ServiceName</B> at <code>$URL</code> is not responding or returned an unexpected status code.<BR>Status code: <B>$ResponseCode</B></P><P>Generated by <B>$Hostname</B></P>"
    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
}
