# Description: Checks a list of Windows services and emails an alert if any are stopped
# Requirements: Permission to query services on the target host
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'service-monitor@domain.local',
    [string]$ToAddress   = 'ops@domain.local',
    [string[]]$ServiceList = @(
        'YourServiceName1',   # Replace with the actual service names to monitor
        'YourServiceName2'
    )
)

$Hostname = [System.Net.Dns]::GetHostName()
$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$DataTable = New-Object System.Data.DataTable
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Service', ([string])))
$DataTable.Columns.Add((New-Object System.Data.DataColumn 'Status',  ([string])))

foreach ($ServiceName in $ServiceList) {
    $Svc = Get-Service $ServiceName -ErrorAction SilentlyContinue
    if ($Svc) {
        $Row = $DataTable.NewRow(); $Row.Service = $Svc.DisplayName; $Row.Status = $Svc.Status
        $DataTable.Rows.Add($Row)
    }
}

$Stopped = $DataTable | Where-Object { $_.Status -eq 'Stopped' }
if ($Stopped) {
    $Names = ($Stopped.Service) -join ', '
    $Email.Subject = "Service(s) Stopped on $Hostname`: $Names"
    $Email.Body    = "<P>The following service(s) are in a stopped state on <B>$Hostname</B>:<BR><B>$Names</B></P><P>Generated by <B>$Hostname</B></P>"
    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
}
