# Description: Uploads specific dated export files (e.g. database exports named with a date) to a
#              remote FTP/SFTP server via WinSCP. Emails a status report.
# Requirements: WinSCP installed, pre-configured WinSCP session
# Pattern: Date-based filename filter → WinSCP command file → upload → log parse → move Sent → email
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'db-export@domain.local',
    [string[]]$ToAddresses   = @('ops@domain.local'),
    [string]$WinSCPSession   = 'RemoteServer',
    [string]$RemoteDirectory = '/inbound',
    [string]$WinSCPExe       = 'C:\Program Files (x86)\WinSCP\WinSCP.com',
    [string]$ScriptWorkDir   = 'C:\Scripts\DBExport',
    [string]$SourcePath      = '\\fileserver\share\DBExports',
    [string]$SentPath        = '\\fileserver\share\DBExports\Sent',
    # Expected filename patterns — update to match your export naming convention
    [string[]]$FilenamePatterns = @('export_data_{0}.csv', 'export_summary_{0}.csv')  # {0} = FileDate
)

$DayOfWeek = (Get-Date).DayOfWeek
$FileDate  = if ($DayOfWeek -eq 'Monday') { Get-Date (Get-Date).AddDays(-3) -Format yyyyMMdd } else { Get-Date (Get-Date).AddDays(-1) -Format yyyyMMdd }
$WinSCPComFile = Join-Path $ScriptWorkDir 'WinSCP-Command-File.txt'
$WinSCPLog     = Join-Path $ScriptWorkDir "WinSCP-$FileDate.log"
$Hostname      = [System.Net.Dns]::GetHostName()

$ExpectedFiles = $FilenamePatterns | ForEach-Object { Join-Path $SourcePath ($_ -f $FileDate) }
$FileList      = Get-ChildItem $SourcePath | Where-Object { $ExpectedFiles -contains $_.FullName }

if ($FileList.Count -eq 0) { Write-Host 'No matching export files found.'; return }

"open $WinSCPSession"   | Out-File $WinSCPComFile -Encoding Default
'option batch on'       | Out-File $WinSCPComFile -Append -Encoding Default
'option confirm off'    | Out-File $WinSCPComFile -Append -Encoding Default
"CD $RemoteDirectory"   | Out-File $WinSCPComFile -Append -Encoding Default
foreach ($File in $FileList) {
    "Put `"$($File.FullName)`"" | Out-File $WinSCPComFile -Append -Encoding Default
}
'close' | Out-File $WinSCPComFile -Append -Encoding Default
'exit'  | Out-File $WinSCPComFile -Append -Encoding Default

Start-Process -FilePath $WinSCPExe -ArgumentList "/Script=$WinSCPComFile /log=$WinSCPLog" -Wait -NoNewWindow

$Log = Get-Content $WinSCPLog
$Table = New-Object System.Data.DataTable
$Table.Columns.Add('FileName'); $Table.Columns.Add('Status')
$JobFail = $false

foreach ($File in $FileList) {
    $Marker = "Copying `"$($File.FullName)`" to remote directory started."
    $Row = $Table.NewRow()
    $Row.FileName = $File.Name
    if ($Log | Where-Object { $_.EndsWith($Marker) }) {
        $Row.Status = 'Completed'
        Move-Item $File.FullName $SentPath
    } else {
        $Row.Status = 'Failed'; $JobFail = $true
    }
    $Table.Rows.Add($Row)
}

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
foreach ($Row in $Table) { $HTMLTable += "<tr><td>$($Row.FileName)</td><td>$($Row.Status)</td></tr>" }
$HTMLTable += '</table>'

$Email = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'DB Export Upload Error' } else { 'DB Export Upload Completed' }
$Email.Body    = "<H1>DB Export Upload Report</H1>$HTMLTable<BR>Generated by <B>$Hostname</B>"
if ($JobFail) { $Email.Attachments.Add($WinSCPLog) }
(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
