# Description: Uploads files from multiple local directories to corresponding remote SFTP directories using WinSCP.
#              Parses the WinSCP log to confirm each file transferred, moves successes to a Sent folder,
#              and emails a per-file status report.
# Requirements: WinSCP installed, pre-configured WinSCP session (set up in WinSCP UI)
# Pattern: Multi-directory → WinSCP command file → log parse → move on success → email report
param(
    [string]$SMTPServer     = 'smtp.domain.local',
    [string]$FromAddress    = 'ftp-monitor@domain.local',
    [string]$ToAddress      = 'ops@domain.local',
    [string]$WinSCPExe      = 'C:\Program Files (x86)\WinSCP\WinSCP.com',
    [string]$WinSCPSession  = 'MyFTPSession',          # Pre-configure this session in WinSCP
    [string]$ScriptWorkDir  = 'C:\Scripts\FTPUploads',
    [string]$SentPath       = 'C:\Scripts\FTPUploads\Sent'
)

# Map of local source directories to remote SFTP paths
# Key = remote SFTP directory, Value = local source folder
$DirectoryMap = [ordered]@{
    '/REMOTE_DIR_1' = '\\fileserver\share\SourceFolder1'
    '/REMOTE_DIR_2' = '\\fileserver\share\SourceFolder2'
    '/REMOTE_DIR_3' = '\\fileserver\share\SourceFolder3'
}

$Date           = Get-Date -UFormat '%Y%m%d_%H%M%S'
$WinSCPComFile  = Join-Path $ScriptWorkDir 'FTPCommandFile.txt'
$WinSCPLog      = Join-Path $ScriptWorkDir "WinSCP-$Date.log"
$Hostname       = [System.Net.Dns]::GetHostName()
$FilesToSend    = $false

if (-not (Test-Path $SentPath)) { New-Item $SentPath -ItemType Directory | Out-Null }

"open $WinSCPSession"  | Out-File $WinSCPComFile -Encoding Default
'option batch on'      | Out-File $WinSCPComFile -Append -Encoding Default
'option confirm off'   | Out-File $WinSCPComFile -Append -Encoding Default

$AllFiles = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

foreach ($Entry in $DirectoryMap.GetEnumerator()) {
    $Files = Get-ChildItem -Path $Entry.Value -Recurse -File -ErrorAction SilentlyContinue
    if ($Files.Count -gt 0) {
        $FilesToSend = $true
        "cd $($Entry.Key)" | Out-File $WinSCPComFile -Append -Encoding Default
        foreach ($File in $Files) {
            "put `"$($File.FullName)`"" | Out-File $WinSCPComFile -Append -Encoding Default
            $AllFiles.Add($File)
        }
    }
}

if ($FilesToSend) {
    'close' | Out-File $WinSCPComFile -Append -Encoding Default
    'exit'  | Out-File $WinSCPComFile -Append -Encoding Default
    Start-Process -FilePath $WinSCPExe -ArgumentList "/Script=$WinSCPComFile /log=$WinSCPLog" -Wait -NoNewWindow
}

$Table = New-Object System.Data.DataTable
$Table.Columns.Add('FileName'); $Table.Columns.Add('Status')
$JobFail = $false

if ($FilesToSend) {
    $Log = Get-Content $WinSCPLog
    foreach ($File in $AllFiles) {
        $Marker    = "Transfer done: '$($File.FullName)'"
        $Completed = $Log | Where-Object { $_.Contains($Marker) }
        $Row = $Table.NewRow()
        $Row.FileName = $File.Name
        if ($Completed) {
            $Row.Status = 'Completed'
            Move-Item $File.FullName $SentPath -Force
        } else {
            $Row.Status = 'Failed'; $JobFail = $true
        }
        $Table.Rows.Add($Row)
    }

    $HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
    foreach ($Row in $Table) { $HTMLTable += "<tr><td>$($Row.FileName)</td><td>$($Row.Status)</td></tr>" }
    $HTMLTable += '</table>'

    $Email         = New-Object Net.Mail.MailMessage
    $Email.From    = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
    $Email.To.Add($ToAddress); $Email.IsBodyHtml = $true
    $Email.Subject = if ($JobFail) { 'SFTP Upload Error' } else { 'SFTP Upload Completed' }
    $Email.Body    = "<H1>SFTP Upload Report</H1>$HTMLTable<BR>Generated by <B>$Hostname</B>"
    (New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
}
