# Description: Uploads files (PDF, ZIP) to a date-structured remote folder via WinSCP.
#              Parses the WinSCP log to confirm each file transferred; emails a status report.
# Requirements: WinSCP installed, pre-configured WinSCP session
# Pattern: Date-based source path → WinSCP command file → log parse → move on success → email report
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'sftp-upload@domain.local',
    [string[]]$ToAddresses   = @('ops@domain.local'),
    [string]$WinSCPSession   = 'RemoteServer',        # Pre-configured WinSCP session
    [string]$RemoteDirectory = '/outbound',
    [string]$WinSCPExe       = 'C:\Program Files (x86)\WinSCP\WinSCP.com',
    [string]$ScriptWorkDir   = 'C:\Scripts\SFTPUpload',
    # Source path supports date format strings evaluated at runtime
    [string]$SourcePathTemplate = '\\fileserver\share\{0}\{1}\',  # {0}=Year, {1}=MonthYear
    [string[]]$FileExtensions   = @('*.pdf', '*.zip')
)

$Year      = Get-Date -UFormat '%Y'
$MonthYear = Get-Date -UFormat '%b %Y'
$Date      = Get-Date -UFormat '%d%m%Y'

$SourcePath    = $SourcePathTemplate -f $Year, $MonthYear
$SentPath      = Join-Path $SourcePath 'Sent'
$WinSCPComFile = Join-Path $ScriptWorkDir 'WinSCP-Command-File.txt'
$WinSCPLog     = Join-Path $ScriptWorkDir "Logs\$Date.log"
$Hostname      = [System.Net.Dns]::GetHostName()

if (-not (Test-Path $SentPath))                         { New-Item $SentPath -ItemType Directory | Out-Null }
if (-not (Test-Path (Join-Path $ScriptWorkDir 'Logs'))) { New-Item (Join-Path $ScriptWorkDir 'Logs') -ItemType Directory | Out-Null }

$FileList = Get-ChildItem $SourcePath -Include $FileExtensions -File
if ($FileList.Count -eq 0) { Write-Host 'No files to upload.'; return }

"open $WinSCPSession" | Out-File $WinSCPComFile -Encoding Default
"CD $RemoteDirectory" | Out-File $WinSCPComFile -Append -Encoding Default
foreach ($File in $FileList) {
    "Put `"$($File.FullName)`"" | Out-File $WinSCPComFile -Append -Encoding Default
}
'close' | Out-File $WinSCPComFile -Append -Encoding Default
'exit'  | Out-File $WinSCPComFile -Append -Encoding Default

Start-Process -FilePath $WinSCPExe -ArgumentList "/Script=$WinSCPComFile /log=$WinSCPLog" -Wait

$Log = Get-Content $WinSCPLog
$Table = New-Object System.Data.DataTable
$Table.Columns.Add('FileName'); $Table.Columns.Add('Status')
$JobFail = $false

foreach ($File in $FileList) {
    $Marker = "Transfer done: '$($File.FullName)'"
    $Row = $Table.NewRow()
    $Row.FileName = $File.Name
    if ($Log | Where-Object { $_.Contains($Marker) }) {
        $Row.Status = 'Completed'
        Move-Item $File.FullName $SentPath -Force
    } else {
        $Row.Status = 'Failed'; $JobFail = $true
    }
    $Table.Rows.Add($Row)
}

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
foreach ($Row in $Table) { $HTMLTable += "<tr><td>$($Row.FileName)</td><td>$($Row.Status)</td></tr>" }
$HTMLTable += '</table>'

$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'SFTP Upload Error' } else { 'SFTP Daily Upload Completed' }
$Email.Body    = "<H1>SFTP Upload Report</H1>$HTMLTable<BR>Generated by <B>$Hostname</B>"

(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
