# Description: Downloads files from a remote SFTP server via a WinSCP script file, compares downloaded
#              files against what was available, and copies successful downloads to a data warehouse path.
#              Emails a status report; exits early if no new files are found.
# Requirements: WinSCP installed, WinSCP session pre-configured, a WinSCP GET script file
# Pattern: WinSCP download → log parse for availability → compare → warehouse copy → email report
param(
    [string]$SMTPServer       = 'smtp.domain.local',
    [string]$FromAddress      = 'sftp-download@domain.local',
    [string[]]$ToAddresses    = @('ops@domain.local'),
    [string]$WinSCPExe        = 'C:\Program Files (x86)\WinSCP\WinSCP.com',
    [string]$WinSCPGetScript  = 'C:\Scripts\DataDownload\WinSCP-Get.txt',  # WinSCP script that does the download
    [string]$LocalDownloadPath = 'C:\Scripts\DataDownload\Downloaded',
    [string]$WarehousePath    = '\\fileserver\DataWarehouse\ImportFiles',
    [string]$LogPath          = 'C:\Scripts\DataDownload\Download.log',
    [string]$FileExtension    = '.csv'
)

$Hostname     = [System.Net.Dns]::GetHostName()
$RunningUser  = "$env:USERDOMAIN\$env:USERNAME"
$JobFail      = $false

# Clear previously downloaded files
Get-ChildItem $LocalDownloadPath -Recurse -File | Remove-Item -ErrorAction SilentlyContinue

# Run WinSCP download
Start-Process -FilePath $WinSCPExe -NoNewWindow -ArgumentList "/Script=$WinSCPGetScript" -Wait -RedirectStandardOutput $LogPath

# Check if no files were available
if (Select-String -Path $LogPath -Pattern 'No file matching') { exit }

# Parse log to find available files
$LogContent = Get-Content $LogPath
$AvailableFiles = foreach ($Line in $LogContent) {
    $Idx = $Line.IndexOf($FileExtension)
    if ($Idx -gt 0) { $Line.Substring(0, $Idx + $FileExtension.Length) }
}

$DownloadedFiles = Get-ChildItem $LocalDownloadPath -Recurse -File
$Comparison      = Compare-Object -ReferenceObject $AvailableFiles -DifferenceObject $DownloadedFiles.Name
if ($Comparison.Count -gt 0) { $JobFail = $true }

# Copy successfully downloaded files to warehouse
Copy-Item "$LocalDownloadPath\*$FileExtension" -Destination $WarehousePath -Force

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true

if ($JobFail) {
    $MissingTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
    foreach ($File in $Comparison) { $MissingTable += "<tr><td>$($File.InputObject)</td><td>Not Downloaded</td></tr>" }
    $MissingTable += '</table>'
    $Email.Subject = 'SFTP Download Incomplete or Failed'
    $Email.Body    = "<P>Some files were not downloaded.</P>$MissingTable<P>Generated by <B>$Hostname</B> as <B>$RunningUser</B></P>"
    $Email.Attachments.Add($LogPath)
} else {
    $Table = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
    foreach ($File in $DownloadedFiles) { $Table += "<tr><td>$($File.Name)</td><td>Downloaded</td></tr>" }
    $Table += '</table>'
    $Email.Subject = 'SFTP Download Completed'
    $Email.Body    = "<P>Files downloaded to $WarehousePath</P>$Table<P>Generated by <B>$Hostname</B> as <B>$RunningUser</B></P>"
}

(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
