# Description: Two-phase script: (1) downloads files from a remote SFTP server using WinSCP,
#              (2) uploads different files to a second SFTP server. Emails status for both phases.
# Requirements: WinSCP installed, separate GET and PUT WinSCP script files pre-configured
# Pattern: Phase 1 download (WinSCP script) → verify → Phase 2 upload (command file) → email
param(
    [string]$SMTPServer         = 'smtp.domain.local',
    [string]$FromAddress        = 'sftp-transfer@domain.local',
    [string[]]$ToAddresses      = @('ops@domain.local'),
    [string]$WinSCPExe          = 'C:\Program Files (x86)\WinSCP\WinSCP.com',
    [string]$DownloadScript     = 'C:\Scripts\Transfer\WinSCP-Download.txt',  # WinSCP script for download phase
    [string]$DownloadLogPath    = 'C:\Scripts\Transfer\Download.log',
    [string]$DownloadLocalPath  = 'C:\Scripts\Transfer\Downloaded',
    [string]$DownloadNetworkPath = '\\fileserver\share\DownloadedFiles',
    [string]$UploadSession      = 'UploadServer',     # Pre-configured WinSCP session
    [string]$UploadRemoteDir    = '/incoming',
    [string]$UploadSourcePath   = 'C:\Scripts\Transfer\Upload',
    [string]$UploadSentPath     = 'C:\Scripts\Transfer\Upload\Sent',
    [string]$UploadComFile      = 'C:\Scripts\Transfer\WinSCP-Upload.txt',
    [string]$UploadLogPath      = 'C:\Scripts\Transfer\Upload.log',
    [string]$FileExtension      = '.csv'
)

$Hostname    = [System.Net.Dns]::GetHostName()
$RunningUser = "$env:USERDOMAIN\$env:USERNAME"
$JobFail     = $false
$FileDate    = if ((Get-Date).DayOfWeek -eq 'Monday') { Get-Date (Get-Date).AddDays(-3) -Format yyyyMMdd } else { Get-Date (Get-Date).AddDays(-1) -Format yyyyMMdd }

# === PHASE 1: DOWNLOAD ===
# Clear previous downloads
Get-ChildItem $DownloadLocalPath -Recurse -File | Remove-Item -ErrorAction SilentlyContinue

Start-Process -FilePath $WinSCPExe -NoNewWindow -ArgumentList "/Script=$DownloadScript" -Wait -RedirectStandardOutput $DownloadLogPath

if (Select-String -Path $DownloadLogPath -Pattern 'No file matching') {
    Write-Host 'No files available for download. Skipping download phase.'
} else {
    $LogContent     = Get-Content $DownloadLogPath
    $AvailableFiles = foreach ($Line in $LogContent) {
        $Idx = $Line.IndexOf($FileExtension)
        if ($Idx -gt 0) { $Line.Substring(0, $Idx + $FileExtension.Length) }
    }
    $DownloadedFiles = Get-ChildItem $DownloadLocalPath -Recurse -File
    $Comparison      = Compare-Object -ReferenceObject $AvailableFiles -DifferenceObject $DownloadedFiles.Name
    if ($Comparison.Count -gt 0) { $JobFail = $true }

    Copy-Item "$DownloadLocalPath\*$FileExtension" -Destination $DownloadNetworkPath -Force
}

# === PHASE 2: UPLOAD ===
$UploadFiles = Get-ChildItem "$UploadSourcePath\*$FileExtension" -File | Where-Object { $_.Name -like "*$FileDate*" }

if ($UploadFiles.Count -gt 0) {
    if (-not (Test-Path $UploadSentPath)) { New-Item $UploadSentPath -ItemType Directory | Out-Null }

    "open $UploadSession" | Out-File $UploadComFile -Encoding Default
    "option batch on"     | Out-File $UploadComFile -Append -Encoding Default
    "option confirm off"  | Out-File $UploadComFile -Append -Encoding Default
    "CD $UploadRemoteDir" | Out-File $UploadComFile -Append -Encoding Default
    foreach ($File in $UploadFiles) {
        "Put `"$($File.FullName)`"" | Out-File $UploadComFile -Append -Encoding Default
    }
    'close' | Out-File $UploadComFile -Append -Encoding Default
    'exit'  | Out-File $UploadComFile -Append -Encoding Default

    Start-Process -FilePath $WinSCPExe -ArgumentList "/Script=$UploadComFile /log=$UploadLogPath" -Wait -NoNewWindow

    $Log = Get-Content $UploadLogPath
    foreach ($File in $UploadFiles) {
        $Marker = "Copying `"$($File.FullName)`" to remote directory started."
        if ($Log | Where-Object { $_.EndsWith($Marker) }) {
            Move-Item $File.FullName $UploadSentPath
        } else {
            $JobFail = $true
        }
    }
}

# Email status
$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'SFTP Transfer Error' } else { 'SFTP Transfer Completed' }
$Email.Body    = if ($JobFail) {
    "<P>One or more phases of the SFTP transfer encountered errors. Check logs for details.</P><P>Generated by <B>$Hostname</B> as <B>$RunningUser</B></P>"
} else {
    "<P>SFTP download and upload completed successfully.</P><P>Generated by <B>$Hostname</B> as <B>$RunningUser</B></P>"
}
if ($JobFail) { $Email.Attachments.Add($DownloadLogPath) }

(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
