# Description: Downloads PGP-encrypted files from a remote server using WS_FTP Pro, verifies
#              each file was transferred by parsing the WS_FTP session log, moves to network path,
#              and emails a status report.
# Requirements: WS_FTP Pro 12 installed, pre-configured WS_FTP connection profile, PGP decryption
# Pattern: WS_FTP command file → download → session log parse → move to network path → email
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'sftp-download@domain.local',
    [string[]]$ToAddresses   = @('ops@domain.local'),
    [string]$WSFTPExe        = '"C:\Program Files (x86)\Ipswitch\WS_FTP 12\wsftppro.exe"',
    [string]$WSFTPCommandFile = 'C:\Scripts\BankDownload\WS_FTP-Command-Download.txt',  # WS_FTP macro file
    [string]$WSFTPSessionLog = 'C:\Users\service-account\AppData\Roaming\Ipswitch\WS_FTP\Logs\WS_FTPSession.log',
    [string]$LocalDownloadPath = 'C:\Scripts\BankDownload\Download',
    [string]$NetworkPath     = '\\fileserver\share\BankFiles',
    [string]$ErrorLogPath    = 'C:\Scripts\BankDownload\ErrorLog.log',
    [string[]]$ExcludeFolders = @('Archive', 'Processed', 'Temp')   # Subfolders to skip when listing files
)

$Hostname    = [System.Net.Dns]::GetHostName()
$RunningUser = "$env:USERDOMAIN\$env:USERNAME"
$JobFail     = $false
$Date        = Get-Date -Format ddMMyyy

# Run WS_FTP download via command file
Start-Process -FilePath $WSFTPExe -NoNewWindow -ArgumentList "-m $WSFTPCommandFile" -Wait -RedirectStandardOutput $ErrorLogPath

# List downloaded files (exclude special subfolders)
$DownloadedFiles = Get-ChildItem $LocalDownloadPath -Exclude $ExcludeFolders | Get-ChildItem -Recurse -File

if ($DownloadedFiles.Count -eq 0) { Write-Host 'No files downloaded. Exiting.'; return }

$Table = New-Object System.Data.DataTable
$Table.Columns.Add('FileName'); $Table.Columns.Add('DownloadLocation'); $Table.Columns.Add('Status')

foreach ($File in $DownloadedFiles) {
    $FolderName = Split-Path $File.Directory -Leaf
    $Log        = Get-Content $WSFTPSessionLog
    # WS_FTP session log shows the PGP-encrypted filename; verify it appeared in the log
    $Marker     = "$($File.Name).pgp`" for reading"
    $Verify     = $Marker2 = 'transfer succeeded'
    $Confirmed  = $false

    for ($i = 0; $i -lt $Log.Count; $i++) {
        if ($Log[$i].Contains($Marker) -and ($i + 6) -lt $Log.Count -and $Log[$i + 6].Contains($Verify)) {
            $Confirmed = $true; break
        }
    }

    $Row = $Table.NewRow()
    $Row.FileName = $File.BaseName
    if ($Confirmed) {
        $DestFolder = Join-Path $NetworkPath $FolderName
        if (-not (Test-Path $DestFolder)) { New-Item $DestFolder -ItemType Directory | Out-Null }
        Move-Item $File.FullName $DestFolder -Force
        $Row.DownloadLocation = "$DestFolder\$($File.Name)"
        $Row.Status           = 'Downloaded'
    } else {
        $Row.DownloadLocation = 'N/A'
        $Row.Status           = 'Failed'
        $JobFail              = $true
    }
    $Table.Rows.Add($Row)
}

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Destination</td><td>Status</td></tr>'
foreach ($Row in $Table) { $HTMLTable += "<tr><td>$($Row.FileName)</td><td>$($Row.DownloadLocation)</td><td>$($Row.Status)</td></tr>" }
$HTMLTable += '</table>'

$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'WS_FTP Download Error' } else { 'WS_FTP Download Completed' }
$Email.Body    = "<H1>WS_FTP Download Report</H1>$HTMLTable<BR>Generated by <B>$Hostname</B> as <B>$RunningUser</B>"
if ($JobFail) { $Email.Attachments.Add($ErrorLogPath); $Email.Attachments.Add($WSFTPSessionLog) }
(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
