# Description: Downloads PGP-encrypted banking files from a bank SFTP server via WS_FTP Pro
#              (Xero/accounting system integration pattern). Verifies transfers via session log.
# Requirements: WS_FTP Pro 12, pre-configured WS_FTP connection profile, local PGP tool for decryption
# Pattern: WS_FTP command file download → session log verification → file move → email status
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'bank-download@domain.local',
    [string[]]$ToAddresses   = @('finance@domain.local'),
    [string]$WSFTPExe        = '"C:\Program Files (x86)\Ipswitch\WS_FTP 12\wsftppro.exe"',
    [string]$WSFTPCommandFile = 'C:\Scripts\AccountingDownload\WS_FTP-Download.txt',
    [string]$WSFTPSessionLog = 'C:\Users\service-account\AppData\Roaming\Ipswitch\WS_FTP\Logs\WS_FTPSession.log',
    [string]$LocalPath       = 'C:\Scripts\AccountingDownload\Download',
    [string]$ProcessedPath   = 'C:\Scripts\AccountingDownload\Download\Processed',
    [string]$ErrorLogPath    = 'C:\Scripts\AccountingDownload\ErrorLog.log',
    [string[]]$ExcludeFolders = @('Processed', 'Temp')
)

$Hostname    = [System.Net.Dns]::GetHostName()
$RunningUser = "$env:USERDOMAIN\$env:USERNAME"
$JobFail     = $false
$Date        = Get-Date -Format ddMMyyy

Start-Process -FilePath $WSFTPExe -NoNewWindow -ArgumentList "-m $WSFTPCommandFile" -Wait -RedirectStandardOutput $ErrorLogPath

$DownloadedFiles = Get-ChildItem $LocalPath -Exclude $ExcludeFolders | Get-ChildItem -Recurse -File

if ($DownloadedFiles.Count -eq 0) { Write-Host 'No files downloaded.'; return }

if (-not (Test-Path $ProcessedPath)) { New-Item $ProcessedPath -ItemType Directory | Out-Null }

$Table = New-Object System.Data.DataTable
$Table.Columns.Add('FileName'); $Table.Columns.Add('Destination'); $Table.Columns.Add('Status')

foreach ($File in $DownloadedFiles) {
    $FolderName = Split-Path $File.Directory -Leaf
    $Log        = Get-Content $WSFTPSessionLog
    $Marker     = "$($File.Name).pgp`" for reading"
    $Verify     = 'transfer succeeded'
    $Confirmed  = $false

    for ($i = 0; $i -lt $Log.Count; $i++) {
        if ($Log[$i].Contains($Marker) -and ($i + 6) -lt $Log.Count -and $Log[$i + 6].Contains($Verify)) {
            $Confirmed = $true; break
        }
    }

    $Row = $Table.NewRow()
    $Row.FileName = $File.BaseName
    if ($Confirmed) {
        $Dest = Join-Path $ProcessedPath "$FolderName\"
        if (-not (Test-Path $Dest)) { New-Item $Dest -ItemType Directory | Out-Null }
        Move-Item $File.FullName $Dest -Force
        $Row.Destination = $Dest
        $Row.Status      = 'Downloaded'
    } else {
        $Row.Destination = 'N/A'
        $Row.Status      = 'Failed'
        $JobFail         = $true
    }
    $Table.Rows.Add($Row)
}

$HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Destination</td><td>Status</td></tr>'
foreach ($Row in $Table) { $HTMLTable += "<tr><td>$($Row.FileName)</td><td>$($Row.Destination)</td><td>$($Row.Status)</td></tr>" }
$HTMLTable += '</table>'

$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'Bank Download Error' } else { 'Bank Download Completed' }
$Email.Body    = "<H1>Bank Download Report</H1>$HTMLTable<BR>Generated by <B>$Hostname</B> as <B>$RunningUser</B>"
if ($JobFail) { $Email.Attachments.Add($ErrorLogPath); $Email.Attachments.Add($WSFTPSessionLog) }
(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
