# Description: Uploads banking files (ABA direct credit/debit, AFI NZ format) to a bank SFTP server
#              via WS_FTP Pro. Verifies each file transferred via session log; emails status report.
# Requirements: WS_FTP Pro 12, pre-configured connection profiles (one per file type/destination)
# Pattern: Collect ABA/AFI files → WS_FTP command file → upload → log parse → move Sent → email
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'bank-upload@domain.local',
    [string[]]$ToAddresses   = @('finance@domain.local', 'ops@domain.local'),
    [string]$WSFTPExe        = '"C:\Program Files (x86)\Ipswitch\WS_FTP 12\wsftppro.exe"',
    [string]$WSFTPSessionLog = 'C:\Users\service-account\AppData\Roaming\Ipswitch\WS_FTP\Logs\WS_FTPSession.log',
    [string]$WinSCPComFile   = 'C:\Scripts\BankUpload\WS_FTP-Command-Upload.txt',
    [string]$ErrorLogPath    = 'C:\Scripts\BankUpload\ErrorLog.log',
    # Source folders for each file type — key = local folder name (also used as remote subfolder), value = local path
    [hashtable]$SourceFolders = @{
        'DirectCredit'  = '\\fileserver\share\BankFiles\DirectCredit'
        'DirectDebit'   = '\\fileserver\share\BankFiles\DirectDebit'
        'NZTransfers'   = '\\fileserver\share\BankFiles\NZTransfers'
    },
    # WS_FTP profile names for each file type
    [hashtable]$WSFTPProfiles = @{
        'DirectCredit' = 'BankPROD'
        'DirectDebit'  = 'BankPROD'
        'NZTransfers'  = 'BankNZPROD'
    }
)

$Hostname = [System.Net.Dns]::GetHostName()
$JobFail  = $false

if (Test-Path $WinSCPComFile) { Remove-Item $WinSCPComFile }

$AllFiles = [System.Collections.Generic.List[PSCustomObject]]::new()

foreach ($Entry in $SourceFolders.GetEnumerator()) {
    $Files = Get-ChildItem $Entry.Value -Include *.aba, *.ABA, *.afi -File
    foreach ($File in $Files) {
        $Profile = $WSFTPProfiles[$Entry.Key]
        $Folder  = $Entry.Key
        "-s local:$($File.FullName) -d ${Profile}:/$Folder/" | Out-File $WinSCPComFile -Append -Encoding UTF8
        $AllFiles.Add([PSCustomObject]@{ File = $File; Profile = $Profile; Folder = $Folder; SentPath = (Join-Path $Entry.Value 'Sent') })
    }
}

if ($AllFiles.Count -eq 0) { Write-Host 'No banking files found. Nothing to upload.'; return }

# Ensure Sent subfolders exist
$AllFiles | ForEach-Object { if (-not (Test-Path $_.SentPath)) { New-Item $_.SentPath -ItemType Directory | Out-Null } }

# Encode command file without BOM (required by some banking systems)
$Content = Get-Content $WinSCPComFile
[System.IO.File]::WriteAllLines($WinSCPComFile, $Content, [System.Text.UTF8Encoding]::new($false))

Start-Process -FilePath $WSFTPExe -ArgumentList " -m $WinSCPComFile" -Wait -NoNewWindow -RedirectStandardOutput $ErrorLogPath

$Log    = Get-Content $WSFTPSessionLog
$Tables = @{}
foreach ($Folder in $SourceFolders.Keys) {
    $Tables[$Folder] = New-Object System.Data.DataTable
    $Tables[$Folder].Columns.Add('FileName'); $Tables[$Folder].Columns.Add('Status')
}

foreach ($Item in $AllFiles) {
    $ParseLine = "Opening remote file `"/$($Item.Folder)/$($Item.File.BaseName)"
    $Verify    = 'transfer succeeded'
    $Confirmed = $false

    for ($i = 0; $i -lt $Log.Count; $i++) {
        if ($Log[$i].Contains($ParseLine) -and ($i + 4) -lt $Log.Count -and $Log[$i + 4].Contains($Verify)) {
            $Confirmed = $true; break
        }
    }

    $Row = $Tables[$Item.Folder].NewRow()
    $Row.FileName = $Item.File.BaseName
    if ($Confirmed) {
        $Row.Status = 'Completed'
        Move-Item $Item.File.FullName $Item.SentPath -Force
    } else {
        $Row.Status = 'Failed'; $JobFail = $true
    }
    $Tables[$Item.Folder].Rows.Add($Row)
}

$HTMLBody = '<H1>Bank File Upload Report</H1>'
foreach ($Folder in $Tables.Keys) {
    $HTMLBody += "<H3>$Folder</H3>"
    $T = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>File</td><td>Status</td></tr>'
    foreach ($Row in $Tables[$Folder]) { $T += "<tr><td>$($Row.FileName)</td><td>$($Row.Status)</td></tr>" }
    $HTMLBody += $T + '</table><BR>'
}
$HTMLBody += "<P>Generated by <B>$Hostname</B></P>"

$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true
$Email.Subject = if ($JobFail) { 'Bank File Upload Error' } else { 'Bank File Upload Completed' }
$Email.Body    = $HTMLBody
if ($JobFail) { $Email.Attachments.Add($ErrorLogPath); $Email.Attachments.Add($WSFTPSessionLog) }
(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
