# Description: Renames a file with a timestamp before uploading via WS_FTP Pro, then emails status.
#              Useful when the remote server expects unique filenames based on upload time.
# Requirements: WS_FTP Pro 12 installed (Ipswitch), pre-configured WS_FTP profile
# Pattern: Check for file → rename with timestamp → WS_FTP upload → email status
param(
    [string]$SMTPServer      = 'smtp.domain.local',
    [string]$FromAddress     = 'sftp-upload@domain.local',
    [string[]]$ToAddresses   = @('ops@domain.local'),
    [string]$WSFTPExe        = '"C:\Program Files (x86)\Ipswitch\WS_FTP 12\wsftppro.exe"',
    [string]$WSFTPProfile    = 'RemoteServer',      # Pre-configured WS_FTP connection profile
    [string]$SourcePath      = '\\fileserver\share\Outbound',
    [string]$SentPath        = '\\fileserver\share\Outbound\Sent',
    [string]$SourceFilename  = 'dataexport.csv',    # The fixed filename to watch for
    [string]$RemotePath      = '/incoming/',
    [string]$FilePrefix      = 'data'               # Prefix for the renamed file
)

$Hostname = [System.Net.Dns]::GetHostName()
$SourceFile = Join-Path $SourcePath $SourceFilename

if (-not (Test-Path $SourceFile)) { Write-Host 'Source file not found. Nothing to upload.'; return }

$Timestamp   = (Get-Date).ToString('yyyyMMdd_HHmmss')
$RenamedFile = Join-Path $SourcePath ($FilePrefix + '_' + $Timestamp + '.csv')
Rename-Item $SourceFile $RenamedFile

$WSFTPArgs = " -s local:$RenamedFile -d ${WSFTPProfile}:$RemotePath -move $SentPath"
$Process   = Start-Process -FilePath $WSFTPExe -ArgumentList $WSFTPArgs -Wait -NoNewWindow -PassThru

$Email      = New-Object Net.Mail.MailMessage
$Email.From = $FromAddress; $Email.Sender = $FromAddress; $Email.ReplyTo = $FromAddress
foreach ($To in $ToAddresses) { $Email.To.Add($To) }
$Email.IsBodyHtml = $true

if ($Process.ExitCode -gt 0) {
    $Email.Subject = 'WS_FTP Upload Error'
    $Email.Body    = "<P>WS_FTP returned exit code $($Process.ExitCode). Check the WS_FTP session log for details.</P><P>File: $RenamedFile</P><P>Generated by <B>$Hostname</B></P>"
} else {
    $Email.Subject = 'WS_FTP Upload Completed'
    $Email.Body    = "<P>Successfully uploaded <B>$(Split-Path $RenamedFile -Leaf)</B>.</P><P>Generated by <B>$Hostname</B></P>"
}
(New-Object Net.Mail.SmtpClient($SMTPServer)).Send($Email)
