# Description: Daily Active Directory health check report sent via email
# Requirements: ActiveDirectory module, SMTP relay access
param(
    [string]$SMTPServer   = 'smtp.domain.local',
    [string]$FromAddress  = 'ad-reports@domain.local',
    [string]$ToAddress    = 'admin@domain.local'
)

$Email          = New-Object Net.Mail.MailMessage
$Email.From     = $FromAddress
$Email.Sender   = $FromAddress
$Email.ReplyTo  = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$Hostname = [System.Net.Dns]::GetHostName()
$Today    = Get-Date -UFormat '%D'

# --- Build report body here ---
$EmailBody = "<BR>This report was generated by <B>$Hostname</B> on $Today"

$Email.Subject = "Daily AD Report - $Today"
$Email.Body    = $EmailBody

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
