# Description: Generates a report of DPM tapes ready for offsite rotation and emails it with an HTML attachment
# Requirements: DPM PowerShell module (loaded from DPM install path), run on DPM server or with remote access
param(
    [string]$SMTPServer  = 'smtp.domain.local',
    [string]$FromAddress = 'dpm-reports@domain.local',
    [string]$ToAddress   = 'ops@domain.local',
    [string]$DPMServer   = 'dpm-server.domain.local',
    [string]$ReportPath  = 'C:\Scripts\OffsiteReadyTapes.html'
)

$installPath    = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Microsoft Data Protection Manager\Setup' 'UIInstallPath').UIInstallPath
$dpmModulePath  = $installPath + 'Modules\DataProtectionManager\DataProtectionManager.psd1'
Import-Module $dpmModulePath

$Hostname   = [System.Net.Dns]::GetHostName()
$Today      = Get-Date -UFormat '%D'

$Email         = New-Object Net.Mail.MailMessage
$Email.From    = $FromAddress
$Email.Sender  = $FromAddress
$Email.ReplyTo = $FromAddress
$Email.To.Add($ToAddress)
$Email.IsBodyHtml = $true

$AllLibraries = Get-DPMLibrary -DPMServerName $DPMServer
$AllTapes     = Get-Tape -DPMLibrary $AllLibraries
$ReadyTapes   = $AllTapes | Sort-Object -Descending CreationDate |
                Where-Object { $_.IsOffsiteReady -and $_.GetDatasetLifeStatus() -eq 'valid' }

$HTMLReport = "<HTML><Title>DPM Report for $Today</Title><H1>Tapes Ready for Offsite on $Today</H1><BR>"
$TapeCount  = 0

foreach ($Tape in $ReadyTapes) {
    $TapeCount++
    $DataTable = New-Object System.Data.DataTable
    foreach ($Col in @('BackupTime','Computer','Name','Type')) {
        $DataTable.Columns.Add((New-Object System.Data.DataColumn $Col, ([string])))
    }

    $HTMLReport += "<Table style='width:300px'><TR><TD>Slot:</TD><TD><B>$($Tape.Location.ID)</B></TD></TR><TR><TD>Barcode:</TD><TD><B>$($Tape.Barcode.Value)</B></TD></TR><TR><TD>Data Written:</TD><TD><B>$($Tape.DataWrittenDisplayString)</B></TD></TR></TABLE><BR>"

    foreach ($RP in (Get-RecoveryPoint $Tape | Sort-Object DataSource)) {
        $Row            = $DataTable.NewRow()
        $Row.BackupTime = $RP.BackupTime.ToString('dd/MM/yyyy HH:mm')
        $Row.Computer   = $RP.DataSource.Computer
        $Row.Name       = $RP.DataSource.Name
        $Row.Type       = $RP.DataSource.Type.Name
        $DataTable.Rows.Add($Row)
    }

    $HTMLTable = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table><tr><td>Backup Time</td><td>Computer</td><td>Object</td><td>Type</td></tr>'
    foreach ($Source in ($DataTable | Sort-Object Computer)) {
        $HTMLTable += "<tr><td>$($Source.BackupTime)</td><td>$($Source.Computer)</td><td>$($Source.Name)</td><td>$($Source.Type)</td></tr>"
    }
    $HTMLTable  += '</table><BR>'
    $HTMLReport += $HTMLTable
}
$HTMLReport | Out-File $ReportPath

$Summary = $ReadyTapes | Select-Object Location, TapeBarcode, CreationDate, DataWrittenDisplayString | Sort-Object -Descending CreationDate

if ($TapeCount -gt 0) {
    $HTMLBody = '<style>table,th,td{border:1px solid black;border-collapse:collapse;}</style><table style="width:500px"><tr><td>Slot</td><td>Barcode</td><td>Date</td><td>Data Written</td></tr>'
    foreach ($Tape in $Summary) {
        $HTMLBody += "<tr><td align=center>$($Tape.Location.ID)</td><td align=center>$($Tape.TapeBarcode.Value)</td><td align=center>$($Tape.CreationDate.ToString('dd/MM/yyyy HH:mm'))</td><td align=center>$($Tape.DataWrittenDisplayString)</td></tr>"
    }
    $HTMLBody   += '</table>'
    $Email.Subject = 'DPM Tapes Ready for Offsite'
    $Email.Body    = "Tapes ready for offsite on $Today.<BR><BR>$HTMLBody<BR>Generated by <B>$Hostname</B>"
    $Email.Attachments.Add($ReportPath)
} else {
    $Email.Subject = 'No DPM Tapes Ready for Offsite'
    $Email.Body    = 'There are no tapes ready for offsite today.'
}

$Smtp = New-Object Net.Mail.SmtpClient($SMTPServer)
$Smtp.Send($Email)
